tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - https://raw.githubusercontent.com/micado-scale/tosca/v0.x.2/micado_types.yaml


topology_template:
  node_templates:
    nginxapp:
      type: tosca.nodes.MiCADO.Container.Application.Docker
      properties:
         image: nginx
         ports: ## ports to be open on the container
           - target: "8080"
             type: NodePort
           - target: "9300"
      interfaces:
        Kubernetes:
          create:
            implementation: Deployment
            inputs: 
              resources:
                requests:
                  cpu: "200m"


  outputs: ## this provide the output to the user, it can be queried by the MiCADO toscasubmitter
    ports:
      value: { get_attribute: [ nginxapp, port ]}


