tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - https://raw.githubusercontent.com/micado-scale/tosca/v0.x.2/micado_types.yaml


topology_template:
  node_templates:
    cqueue_worker:
      type: tosca.nodes.MiCADO.Container.Application.Docker
      properties:
        image: cqueue-worker
        env:
        - name: BROKER
          value: amqp://guest:guest@cqueue.server.ip.address:5672
        - name: RESULT_BACKEND
          value: redis://cqueue.server.ip.address:6379
      requirements:
        - volume:
            node: docker-binary-host-vol
            relationship:
              type: tosca.relationships.AttachesTo
              properties:
                location: /usr/bin/docker
        - volume:
            node: docker-socket-host-vol
            relationship:
              type: tosca.relationships.AttachesTo
              properties:
                location: /var/run/docker.sock
      interfaces:
        Kubernetes:
          create:
            implementation: Deployment
            inputs: 
              restartPolicy: "Always"

    docker-binary-host-vol: ## this is the description of a volume to be mounted on a node
      type: tosca.nodes.MiCADO.Container.Volume
      properties:
        name: docker-bin
      interfaces:
        Kubernetes:
          create:
            inputs:
              hostPath:
                path: /usr/bin/docker

    docker-socket-host-vol: ## this is the description of a volume to be mounted on a node
      type: tosca.nodes.MiCADO.Container.Volume
      properties:
        name: docker-socket
      interfaces:
        Kubernetes:
          create:
            inputs:
              hostPath:
                path: /var/run/docker.sock
